@hostname = localhost
@port = 3333
@baseURL = http://{{hostname}}:{{port}}

###

GET {{baseURL}}/courses

###
POST {{baseURL}}/courses
Content-Type: application/json

{
  "title": "React Native"
}
###

GET {{baseURL}}/courses/61b1e4d6-87bb-4b4f-a083-9ba8bd8f619f

### 