# docker-compose.yml - Required Services Configuration
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_nodejs
    ports:
      - "5432:5432"
    volumes: 
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql